/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  Antonio
 * Created: 27-may-2020
 */

INSERT INTO APP.ACTIVIDAD VALUES(1,'Recogida de caca de perro','PENDIENTE','2020-05-12','2021-05-13','EN UN LUGAR DE LA MANCHA', 'RECOGIDA DE MIERDAS','VOLUNTARIADO','ong1','CIENTIFICO1' )

INSERT INTO APP.INFORME  VALUES (1, 'REALIZADO CORRECTAMENTE','LIMPIEZA, AYUDA A NIÑOS','30 HORAS',1, 'Anastasia')

INSERT INTO APP.ACTIVIDAD VALUES (1,'Recogida de caca de perro','PENDIENTE','2020-05-12','2021-05-13','EN UN LUGAR DE LA MANCHA', 'RECOGIDA DE MIERDAS','VOLUNTARIADO',1, 'CIENTIFICO1')

INSERT INTO APP.ACTIVIDAD (ID, DESCRIPCION, ESTADO, FECHA_FIN, FECHA_INICIO, LUGAR, NOMBRE, TIPO, ONG_ID, RESPONSABLE_ID ) VALUES (16, 'Alimentar a los sin techo', 'ACEPTADA','2020-06-09','2021-06-09', 'Barriada de la luz', 'Reparto alimentos', 'ApS', 2, 'INVESTIGADOR1')

INSERT INTO APP.SOLICITUD_ACTIVIDAD (ID, ESTADO, FECHA_SOLICITUD, ACTIVIDAD_ID,USUARIO_ID) VALUES (800, 'por confirmar', '2020-06-04', 1)

INSERT INTO APP.INFORME  VALUES (1, 'REALIZADO CORRECTAMENTE','LIMPIEZA, AYUDA A NIÑOS','30 HORAS',1, 'Anastasia')

INSERT INTO APP.INFORME (ID, EVALUACION, TAREAS_REALIZADAS, TIEMPO_EMPLEADO, ACTIVIDAD_ID, USUARIO_ID) VALUES (321, 'REALIZADA INCORRECTAMENTE', 'reparto de alimentos a distintos puntos', 'tres días', 16, 'Actriz')
INSERT INTO APP.USUARIO  (USUARIO, APELLIDOS, CONTRASENIA, DNI, EMAIL, ESTUDIOS, FECHA_NACIMIENTO, IDIOMA, NOMBRE, ROL) VALUES ('Detective', 'Holmes', 'pass12341', 77453728, 'usuario1@hotmail.com', 'psicologia', '1800-11-30','ingles', 'Sherlock', 'NORMAL')
INSERT INTO APP.USUARIO  VALUES('usuario1','usuario1','usuario1',1111111,'usuario1','2020-01-12','usuario1','usuario1','ALUMNO')
INSERT INTO APP.USUARIO (USUARIO,APELLIDOS,CRONTASENIA,DNI,EMAIL,ESTUDIOS,FECHA_NACIMIENTO,IDIOMA,NOMBRE,ROL) VALUES('usuario2','usuario1','usuario1',1111112,'usuario1','2020-01-12','usuario1','usuario2','ALUMNO')
INSERT INTO APP.USUARIO (USUARIO,APELLIDOS,CRONTASENIA,DNI,EMAIL,ESTUDIOS,FECHA_NACIMIENTO,IDIOMA,NOMBRE,ROL) VALUES('usuario3','usuario1','usuario1',1111113,'usuario1','2020-01-12','usuario1','usuario3','ALUMNO')
INSERT INTO APP.USUARIO (USUARIO,APELLIDOS,CRONTASENIA,DNI,EMAIL,ESTUDIOS,FECHA_NACIMIENTO,IDIOMA,NOMBRE,ROL) VALUES('usuario4','usuario1','usuario1',1111114,'usuario1','2020-01-12','usuario1','usuario4','RESPONSABLE')
INSERT INTO APP.USUARIO (USUARIO,APELLIDOS,CRONTASENIA,DNI,EMAIL,ESTUDIOS,FECHA_NACIMIENTO,IDIOMA,NOMBRE,ROL) VALUES('usuario5','usuario1','usuario1',1111115,'usuario1','2020-01-12','usuario1','usuario5','RESPONSABLE')
INSERT INTO APP.USUARIO (USUARIO,APELLIDOS,CRONTASENIA,DNI,EMAIL,ESTUDIOS,FECHA_NACIMIENTO,IDIOMA,NOMBRE,ROL) VALUES('usuario6','usuario1','usuario1',1111116,'usuario1','2020-01-12','usuario1','usuario6','RESPONSABLE')
INSERT INTO APP.USUARIO (USUARIO,APELLIDOS,CRONTASENIA,DNI,EMAIL,ESTUDIOS,FECHA_NACIMIENTO,IDIOMA,NOMBRE,ROL) VALUES('usuario7','usuario1','usuario1',1111117,'usuario1','2020-01-12','usuario1','usuario7','ONG')
INSERT INTO APP.USUARIO (USUARIO,APELLIDOS,CRONTASENIA,DNI,EMAIL,ESTUDIOS,FECHA_NACIMIENTO,IDIOMA,NOMBRE,ROL) VALUES('usuario8','usuario1','usuario1',11111118,'usuario1','2020-01-12','usuario1','usuario8','ONG')
INSERT INTO APP.USUARIO (USUARIO,APELLIDOS,CRONTASENIA,DNI,EMAIL,ESTUDIOS,FECHA_NACIMIENTO,IDIOMA,NOMBRE,ROL) VALUES('usuario9','usuario1','usuario1',11111119,'usuario1','2020-01-12','usuario1','usuario9','ONG')
INSERT INTO APP.USUARIO (USUARIO,APELLIDOS,CRONTASENIA,DNI,EMAIL,ESTUDIOS,FECHA_NACIMIENTO,IDIOMA,NOMBRE,ROL) VALUES('usuario10','usuario1','usuario1',111119,'usuario1','2020-01-12','usuario1','usuario7','NORMAL')
INSERT INTO APP.USUARIO (USUARIO,APELLIDOS,CRONTASENIA,DNI,EMAIL,ESTUDIOS,FECHA_NACIMIENTO,IDIOMA,NOMBRE,ROL) VALUES('usuario11','usuario1','usuario1',111115,'usuario1','2020-01-12','usuario1','usuario8','NORMAL')
INSERT INTO APP.USUARIO (USUARIO,APELLIDOS,CRONTASENIA,DNI,EMAIL,ESTUDIOS,FECHA_NACIMIENTO,IDIOMA,NOMBRE,ROL) VALUES('usuario12','usuario1','usuario1',11117,'usuario1','2020-01-12','usuario1','usuario9','NORMAL')
INSERT INTO APP.ALUMNO VALUES('usuario1',12345,'informatica')
INSERT INTO APP.ALUMNO VALUES('usuario2',123456,'informatica')
INSERT INTO APP.ALUMNO VALUES('usuario3',1234567,'informatica')
INSERT INTO APP.RESPONSABLE_ACTIVIDAD VALUES('usuario4','LCC')
INSERT INTO APP.RESPONSABLE_ACTIVIDAD VALUES('usuario5','LCC')
INSERT INTO APP.RESPONSABLE_ACTIVIDAD VALUES('usuario6','LCC')
INSERT INTO APP.ONG VALUES('usuario7','esto es la descripcion','espana',777888)
INSERT INTO APP.ONG VALUES('usuario8','esto es la descripcion','espana',777888)
INSERT INTO APP.ONG VALUES('usuario9','esto es la descripcion','espana',777888)

INSERT INTO APP.ACTIVIDAD VALUES(2,'Comedor solidario','PENDIENTE','2020-06-13','2020-07-13','HUELVA', 'COMEDOR','VOLUNTARIADO','ong2','resp')

INSERT INTO APP.ACTIVIDAD VALUES(3,'Plantar pinos','TERMINADA','2019-03-10','2019-03-11','Albacete', 'COSECHA','VOLUNTARIADO','ong1','resp')


INSERT INTO APP.SOLICITUD_ACTIVIDAD (ID, ESTADO, FECHA_SOLICITUD, ACTIVIDAD_ID,USUARIO_ID) VALUES (801, 'por confirmar', '2020-01-22', 1)

INSERT INTO APP.SOLICITUD_ACTIVIDAD (ID, ESTADO, FECHA_SOLICITUD, ACTIVIDAD_ID,USUARIO_ID) VALUES (802, 'confirmada', '2020-05-20', 1)


INSERT INTO APP.INFORME  VALUES (2, 'REALIZADO','PLANTAR ÁRBOLES','10 HORAS',1, 'Anastasia')

INSERT INTO APP.INFORME  VALUES (3, 'REALIZADO','REPARTIR COSAS','3 HORAS',1, 'Anastasia')


UPDATE APP.SEQUENCE SEQ_COUNT=1000000